#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    stack=[]
    valleyCount=0
    mountainCount=0
    for step in s:
        if len(stack)>0:
            #check if we are moving in the same direction or not
            if stack[-1]== step:
                stack.append(step)
            else:
                popped=stack.pop()
                #Ihave reached sea level
                if len(stack)==0:
                    if step=='U':
                        valleyCount+=1
                        # print("Valley encountered")
                    else:
                        mountainCount+=1
                        # print("mountain encountered")


        else:
            stack.append(step)

    return valleyCount

if __name__=='__main__':
    n=int(input())
    s=input()
    result=countingValleys(n,s)
    print(str(result))
